windowrule=isfloating:1,width:1200,height:800,appid:nemo
windowrule=isfloating:1,width:800,height:200,appid:org.pulseaudio.pavucontrol
windowrule=isfloating:1,appid:feh
windowrule=isfloating:1,appid:uxn
